# Generated by Django 6.0.2 on 2026-02-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('instituicao', models.CharField(max_length=100)),
                ('emitido_em', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TecHabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('codigo', models.URLField(blank=True)),
                ('tags', models.ManyToManyField(blank=True, to='dezenvolvedor.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Carreira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fim', models.DateField(blank=True, null=True)),
                ('localizacao', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('instituicao', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('habilidades', models.ManyToManyField(blank=True, to='dezenvolvedor.techabilidade')),
            ],
        ),
    ]
