# Generated by Django 6.0.2 on 2026-02-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dezenvolvedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(default=1, upload_to='imagens/'),
            preserve_default=False,
        ),
    ]
