# Generated by Django 6.0.2 on 2026-02-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dezenvolvedor', '0002_projeto_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='tags',
        ),
    ]
