# Generated by Django 6.0.2 on 2026-02-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dezenvolvedor', '0003_remove_projeto_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificacao',
            name='emitido_em',
            field=models.DateField(blank=True, help_text='Formato MM/YYYY', null=True, unique_for_date='emitido_em'),
        ),
    ]
